@echo off
echo 🚀 Starting AI Mastery Week 2 Pipeline...

echo Step 1: Scraping Reviews...
python src\scraping\scraper.py

echo Step 2: Cleaning Text & Normalizing Dates...
python src\preprocessing\cleaner.py

echo Step 3: Validating Cleaned Data...
python src\preprocessing\validator.py

echo Step 4: Sentiment Analysis...
python src\nlp\sentiment.py

echo Step 5: Theme Extraction (LDA)...
python src\nlp\themes.py

echo Step 6: Feature Requests Extraction...
python src\nlp\feature_extractor.py

echo Step 7: Clustering Complaints...
python src\nlp\complaint_clusterer.py

echo Step 8: Inserting into Oracle DB...
python src\database\manager.py

echo Step 9: Generating Report...
python src\reporting\report_generator.py

echo ✅ Pipeline Complete!